services:
  # A Docker web service
  - type: web
    name: udoit
    runtime: image
    image:
      url: ghcr.io/ssilverm/udoit:main
    plan: free
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true
      - key: APP_LMS
        value: canvas
      - key: APP_OAUTH_REDIRECT_PATH
        value: "/authorize/check"
      - key: APP_LTI_REDIRECT_PATH
        value: "/lti/authorize/check"
      - key: APP_LTI_NAME
        value: "UDOIT 3"
      - key: ADMIN_LTI_NAME
        value: "UDOIT 3 Admin"
      - key: USE_DEVELOPMENT_AUTH
        value: "no"
      - key: VERSION_NUMBER
        value: "3.3.1"
      - key: MESSENGER_TRANSPORT_DSN
        value: doctrine://default
      - key: PHPALLY_EXCLUDED_RULES
        value: ""
      - key: BASE_URL
        fromService:
          name: udoit
          property: host
      - key: WEBPACK_PUBLIC_PATH
        value: "/udoit3/build"
      - key: STORE_USER_NAMES
        value: true
      - key: BACKGROUND_COLOR
        value: "#ffffff"
      - key: TEXT_COLOR
        value: "#2D3B45"
      - key: VIMEO_API_KEY
        value: ""
      - key: YOUTUBE_API_KEY
        value: ""
      - key: JWK_BASE_URL
        value: "https://canvas.instructure.com/"
      - key: DATABASE_URL
        fromDatabase:
          name: udoit database
          property: connectionString

databases:
  - name: udoit database
    ipAllowList: [] # only allow internal connections
    plan: free
