services:
  # A Docker web service
  - type: web
    name: udoit
    runtime: image
    image:
      url: ghcr.io/ucfopen/udoit:stable-3.3.x
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: udoit database
          property: connectionString

databases:
  - name: udoit database
    ipAllowList: [] # only allow internal connections
    plan: free


